name = "slack-notification-provider"
language = "rust"
type = "provider"

[provider]
vendor = "Ekko"
version = "0.1.0"
description = "Slack notification provider for blockchain alerts"
protocol = "slack"

[[provider.claims]]
name = "wasmcloud:messaging"
[[provider.claims]]
name = "wasmcloud:keyvalue"

[provider.config]
redis_url = "redis://:redis123@redis-master.ekko.svc.cluster.local:6379"
nats_url = "nats://127.0.0.1:4222"
